name: opengov
recipe: drupal8
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
  php: '7.1'

services:
  appserver:
    build:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT/web/profiles/opengov && composer install"

events:
  post-db-import:
    - appserver:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT/web/profiles/opengov && composer install"
